spring:
  application:
    name: PRODUTOS-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/microsservicos_produtos
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    level: 5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
